version: '3.9'
services:
    f1-fullstack:
        stdin_open: true
        environment:
            - NODE_ENV=production
            - PORT=3000
        build:
            context: .
            dockerfile: Dockerfile
        container_name: f1-fullstack
        ports:
            - '3000:3000'
        restart: always
